import './reference';
import './style.css';
import type {Geography} from './types';
const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
type Member={growth:number;diffusion:number;resistance:number;startKa:number;arrivalKa:(number|null)[];source?:number};
type Fit={draws:number;effectiveSampleSize:number;source:number;valid:number[];rainMean:number[];frames:{ka:number;probability:number[]}[];members:Member[];sites:{name:string;cell:number;status:string;arrivalKa:number[];priorArrivalKa:number[];reachedBy40Ka:number}[];growthFit:{fittedTotalFertility:number;fittedAnnualLogRate:number};assumptions:string[];sources:{title:string;url:string}[];parameterIntervals:Record<string,number[]>};
let geo:Geography,fit:Fit,member:Member|undefined,selected=0,frame=10,playing=false,tickTime=0,drawIndex=0,worker:Worker|undefined;
const canvas=el<HTMLCanvasElement>('map'),ctx=canvas.getContext('2d')!;
const coord=(i:number)=>[20+(i%90+.5)*.5,40-(Math.floor(i/90)+.5)*.5];
function nearest(lon:number,lat:number){let best=Infinity,index=0;fit.valid.forEach((v,i)=>{const [x,y]=coord(i);const d=(x-lon)**2+(y-lat)**2;if(v&&d<best){best=d;index=i;}});return index;}
function value(i:number){if(!member)return fit.frames[frame].probability[i]/255;const a=member.arrivalKa[i];if(a===null||a<fit.frames[frame].ka||!fit.valid[i])return 0;const t=(a-fit.frames[frame].ka)*1000;return 1/(1+99*Math.exp(-member.growth*t));}
function stop(){playing=false;el('play').textContent='▶';el('play').setAttribute('aria-label','Play simulation');}
function view(){const custom=el<HTMLSelectElement>('mode').value==='scenario';el('scenario-controls').hidden=!custom;el('run').textContent=custom?'Run scenario':'Load fitted ensemble';el('view-note').textContent=custom?'Adjust the conditions and run in your browser. Custom scenarios are not refitted to the archaeological evidence.':'Weighted by the Al Wusta minimum-age evidence. Pink shows the chance that this modeled expansion has reached a cell.';}
function draw(){if(!fit||canvas.clientWidth===0)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);const s=Math.min((w-24)/45,(h-24)/45),x=(lon:number)=>w/2+(lon-42.5)*s,y=(lat:number)=>h/2-(lat-17.5)*s;ctx.fillStyle='#d9edf2';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#c4dfe6';ctx.lineWidth=.5;for(let i=20;i<=65;i+=5){ctx.beginPath();ctx.moveTo(x(i),0);ctx.lineTo(x(i),h);ctx.stroke();}ctx.beginPath();geo.polygons.forEach(p=>p.forEach(r=>{r.forEach((pt,i)=>i?ctx.lineTo(x(pt[0]),y(pt[1])):ctx.moveTo(x(pt[0]),y(pt[1])));ctx.closePath();}));ctx.fillStyle='#e8e9df';ctx.fill('evenodd');ctx.strokeStyle='#9eada3';ctx.stroke();
const colors=['#fbd7f0','#f4a7db','#e970c3','#c9389b','#851d66'];let count=0;for(let i=0;i<fit.valid.length;i++){if(!fit.valid[i])continue;const v=value(i);if(v>=.5)count++;if(v<.01)continue;const [lon,lat]=coord(i);ctx.fillStyle=colors[Math.min(4,Math.floor(v*5))];ctx.fillRect(x(lon)-s*.23,y(lat)-s*.23,s*.46,s*.46);}
ctx.textAlign='center';ctx.font='12px Space';for(const [label,lon,lat] of [['SAHARA',25,27],['ARABIA',46,24],['LEVANT',37,34],['INDIAN OCEAN',57,1]] as [string,number,number][]){ctx.fillStyle='#485b52';ctx.fillText(label,x(lon),y(lat));}
for(const site of fit.sites){const [lon,lat]=coord(site.cell);ctx.fillStyle='#20211f';ctx.beginPath();ctx.arc(x(lon),y(lat),3,0,Math.PI*2);ctx.fill();if(site.name==='Al Wusta'){ctx.font='12px Space';ctx.textAlign='left';ctx.fillText(site.name,x(lon)+6,y(lat)-6);}}
const [sx,sy]=coord(member?.source??fit.source);ctx.strokeStyle='#20211f';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(x(sx),y(sy),6,0,Math.PI*2);ctx.stroke();const [ix,iy]=coord(selected);ctx.strokeRect(x(ix)-5,y(iy)-5,10,10);el('occupied').textContent=count.toLocaleString();}
function update(){if(!fit)return;el('year').textContent=String(fit.frames[frame].ka);el<HTMLInputElement>('time').value=String(frame);el('map-layer').textContent=member?'Population density / single scenario':'Probability of arrival / fitted ensemble';el('legend-label').textContent=member?'Local capacity filled':'Probability reached';el('metric-label').textContent=member?'Established cells':'Likely reached cells';el('metric-note').textContent=member?'At least 50% of local capacity':'At least 50% ensemble probability';const [lon,lat]=coord(selected);el('coordinates').textContent=`${lat.toFixed(2)}° N / ${lon.toFixed(2)}° E`;el('cell-value').textContent=fit.valid[selected]?`${Math.round(value(selected)*100)}%`:'No model data';const a=member?.arrivalKa[selected];el('cell-arrival').textContent=member?(a!=null&&a>=40&&a<=120?`Scenario arrival: ${a.toFixed(1)} ka`:'Not reached within the displayed period'): 'Probability that the modeled expansion has reached this cell.';el('arrivals').innerHTML=fit.sites.map(site=>{const a=member?.arrivalKa[site.cell];return `<div class="site-row"><strong>${site.name}</strong><span>${member?(a!=null&&a>=40&&a<=120?a.toFixed(1)+' ka':'Not reached'):`${site.arrivalKa[2].toFixed(1)}–${site.arrivalKa[0].toFixed(1)} ka`}</span><small>${member?'Single scenario':site.status}</small></div>`;}).join('');draw();}
function run(){stop();if(el<HTMLSelectElement>('mode').value==='ensemble'){member=undefined;el('engine-state').textContent='Fitted ensemble';el('run-status').textContent=`${fit.draws.toLocaleString()} draws · effective sample size ${fit.effectiveSampleSize}`;update();return;}worker?.terminate();worker=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});el<HTMLButtonElement>('run').disabled=true;el('run-status').textContent='Calculating expansion…';const origins:Record<string,number[]>={nile:[32.25,15.25],horn:[36.25,9.25],levant:[35.25,31.25]};const [lon,lat]=origins[el<HTMLSelectElement>('origin').value];worker.onmessage=({data})=>{el<HTMLButtonElement>('run').disabled=false;if(data.error){el('run-status').textContent=data.error;return;}member=data;el('engine-state').textContent='Rust / WASM';el('run-status').textContent=`Scenario complete · ${(data.runtime/1000).toFixed(2)}s`;update();};worker.onerror=()=>{el<HTMLButtonElement>('run').disabled=false;el('run-status').textContent='The scenario failed. Try again.';};worker.postMessage({geo,valid:fit.valid,rain:fit.rainMean,source:nearest(lon,lat),growth:Number(el<HTMLInputElement>('growth').value)/100,diffusion:Number(el<HTMLInputElement>('mobility').value),resistance:Number(el<HTMLInputElement>('resistance').value),startKa:Number(el<HTMLInputElement>('departure').value)});}
el('settings').addEventListener('submit',e=>{e.preventDefault();run();});el('mode').addEventListener('change',()=>{view();if(fit&&el<HTMLSelectElement>('mode').value==='ensemble')run();});
for(const id of ['growth','mobility','resistance'])el(id).addEventListener('input',()=>{const v=Number(el<HTMLInputElement>(id).value);el(id+'-value').textContent=id==='growth'?v.toFixed(2)+'%':id==='mobility'?v.toFixed(1)+' km²/yr':v.toFixed(1);el('run-status').textContent='Settings changed · run to apply';});
el('sample').addEventListener('click',()=>{stop();member={...fit.members[drawIndex++%fit.members.length],source:fit.source};el('engine-state').textContent=`Fitted draw ${((drawIndex-1)%fit.members.length)+1}`;el('run-status').textContent='One weighted draw from the fitted ensemble; inspect another or reload the ensemble.';update();});
el('time').addEventListener('input',()=>{stop();frame=Number(el<HTMLInputElement>('time').value);update();});
el('play').addEventListener('click',()=>{if(playing){stop();return;}if(frame===40)frame=0;playing=true;el('play').textContent='Ⅱ';el('play').setAttribute('aria-label','Pause simulation');tickTime=performance.now();requestAnimationFrame(tick);});
function tick(t:number){if(!playing)return;if(t-tickTime>350/Number(el<HTMLSelectElement>('speed').value)){frame++;update();tickTime=t;if(frame===40){stop();return;}}requestAnimationFrame(tick);}
el('rewind').addEventListener('click',()=>{stop();frame=0;update();});canvas.addEventListener('click',e=>{const rect=canvas.getBoundingClientRect(),s=Math.min((rect.width-24)/45,(rect.height-24)/45);const lon=42.5+(e.clientX-rect.left-rect.width/2)/s,lat=17.5-(e.clientY-rect.top-rect.height/2)/s;const c=Math.floor((lon-20)/.5),r=Math.floor((40-lat)/.5);if(c>=0&&c<90&&r>=0&&r<90){selected=r*90+c;update();}});canvas.addEventListener('keydown',e=>{const delta:Record<string,number>={ArrowLeft:-1,ArrowRight:1,ArrowUp:-90,ArrowDown:90};if(e.key in delta){e.preventDefault();selected=Math.max(0,Math.min(8099,selected+delta[e.key]));update();}});
el('export').addEventListener('click',()=>{const data={schema:'dispersal-experiment/v3',calibration:'/calibration.json',dateKa:fit.frames[frame].ka,member:member??null,assumptions:fit.assumptions,parameterIntervals:fit.parameterIntervals,sites:fit.sites};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='dispersal-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);});new ResizeObserver(draw).observe(canvas);view();
async function start(){try{const responses=await Promise.all([fetch('/geography.json'),fetch('/calibration.json')]);if(responses.some(r=>!r.ok))throw Error('Model data could not load. Reload to retry.');[geo,fit]=await Promise.all(responses.map(r=>r.json()));selected=fit.source;el('fit-stats').textContent=`${fit.draws.toLocaleString()} prior draws. Effective sample size after weighting: ${fit.effectiveSampleSize}.`;el('demography').textContent=`A female age-structured model combines the published !Kung mortality coefficients with an approximate modern fertility-age shape. Fitting its fertility scale to the 0.26% annual intrinsic growth target gives a total fertility of ${fit.growthFit.fittedTotalFertility.toFixed(2)}. This calibrates the modern analogue, not ancient fertility. A broad transfer prior then allows ancient growth to differ.`;el('assumptions').innerHTML=fit.assumptions.map(t=>`<li>${t}</li>`).join('');el('citations').innerHTML=fit.sources.map(s=>`<p><a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.title} ↗</a></p>`).join('');const prior=fit.sites[0].priorArrivalKa;el('prior-check').textContent=`Al Wusta: the unweighted median arrival is ${prior[1].toFixed(1)} ka, versus ${fit.sites[0].arrivalKa[1].toFixed(1)} ka after weighting. Prior draws arriving outside120–40ka are outside the experiment’s historical window.`;for(const id of ['run','play','rewind','export','sample'])el<HTMLButtonElement>(id).disabled=false;el<HTMLInputElement>('time').disabled=false;run();}catch(e){el('run-status').textContent=e instanceof Error?e.message:'Could not load the model.';el('engine-state').textContent='Load failed';}}
start();
